listener:
  tcp:
    address: 0.0.0.0
    port: 8888
    secure: false

logger:
  pretty: true
  level: DEBUG

routes:
  - match:
      path: /
    response_headers:
      captain: american
      hawk: eye
    response_body: '{"sample": "response"}'
  - match:
      path: /delay
    response_headers:
      captain: american
      hawk: eye
    response_body: '{"delay": "response"}'
    delay: 30s